### ISSUE TITLE
README File mising

### ISSUE THREAD

**Issue by agehlers** [BCDevOps/openshift-components#2]
Hi, could you please add a README file your repo. All repositories in the BCGOV ORG should have a README file. Reference: https://github.com/bcgov/BC-Policy-Framework-For-GitHub/tree/master/BC-Gov-Org-HowTo and https://github.com/bcgov/BC-Policy-Framework-For-GitHub/blob/master/BC-Gov-Org-HowTo/Cheatsheet.md. Thank you.

**Comment by abbr** [comment]
Repo is obsolete. You can delete or archive. I don't have permission (anymore).

**Comment by agehlers** [comment]
Added Readme file
