### ISSUE TITLE
ZAP Image - Encode html report 

### ISSUE THREAD

**Issue by agehlers** [BCDevOps/openshift-components#9]
f.write (zap.core.htmlreport().encode('utf-8')
Error: 
2018-05-25 00:34:38,804 Unexpected error: <type 'exceptions.UnicodeEncodeError'>
Traceback (most recent call last):
  File "/zap/zap-baseline.py", line 380, in main
    f.write(zap.core.htmlreport())
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0100' in position 497284: ordinal not in range(128)
Issue: 
u0100 is a latin character. py script bails on non utf-8 chars when writing html report.
Resolution:
change  f.write (zap.core.htmlreport() in baseline python script to 
f.write (zap.core.htmlreport().encode('utf-8')

**Comment by lukegonis** [comment]
No longer an issue
